### ISSUE TITLE
Highlight certain repair orders for Fernando

### ISSUE THREAD

**Issue by RoyalDrive** [Royal-Drive/DMS#91] opened 2021-04-15 20:32 UTC
hey jake,

Can we come up with some idea on how to highlight certain repair data? When I print the sheet I take a highligher sharpee and highlight yellow the ones that I need Fernando to do first. Is there a way to do that with the printable document? Maybe have a little check box somewhere to select to make it a priority repair? 

![image](https://user-images.githubusercontent.com/79367027/114934667-cc9d1500-9dff-11eb-8d80-8a316034586d.png)

**Comment by JacobWeisenburger** [comment] 2021-04-17 15:37
Duplicate of #76

**Closed** 2021-05-03 19:14 UTC
Labels: Priority: 5
